version: '3'
services:
  vkbot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/VkAnkiBot
    command:
      - python
      - 'vkbot/main.py'
    environment:
      VK_API_KEY: ${VK_API_KEY}
      VK_GROUP_ID: ${VK_GROUP_ID}
      VK_API_VERSION: ${VK_API_VERSION}
      VK_BOT_MODE: ${VK_BOT_MODE}
      DB_URL: ${DB_URL}
    depends_on:
      - server
      - postgres
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/VkAnkiBot
    command:
      - python
      - 'server/api/main.py'
    environment:
      VK_BOT_MODE: ${VK_BOT_MODE}
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - db/database.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
