version: '3'
services:
  vkbot:
    build:
      context: ./
      dockerfile: ./vkbot/Dockerfile
    volumes:
      - ./vkbot:/vkbot
    command:
      - python
      - 'client.py'
    environment:
      VK_API_KEY: ${VK_API_KEY}
      VK_GROUP_ID: ${VK_GROUP_ID}
      VK_API_VERSION: ${VK_API_VERSION}
