version: '3'
services:
  vkbot:
    build:
      context: ./
      dockerfile: ./vkbot/Dockerfile
    volumes:
      - ./vkbot:/vkbot
    command:
      - python
      - 'main.py'
    environment:
      VK_API_KEY: ${VK_API_KEY}
      VK_GROUP_ID: ${VK_GROUP_ID}
      VK_API_VERSION: ${VK_API_VERSION}
      VK_BOT_MODE: ${VK_BOT_MODE}
    depends_on:
      - server
      - postgres
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/server
    command:
      - python
      - 'api/main.py'
    environment:
      VK_BOT_MODE: ${VK_BOT_MODE}
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - db/database.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
