"""add Statistic table

Revision ID: 6a27245afbe0
Revises: 115665d5364b
Create Date: 2021-02-19 07:00:09.136879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a27245afbe0'
down_revision = '115665d5364b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('win_games', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'games', 'users', ['owner_id'], ['vk_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_table('users_statistic')
    # ### end Alembic commands ###
